// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synapse.Infrastructure;

namespace Synapse.Infrastructure.Migrations
{
    [DbContext(typeof(SynapseDBContext))]
    [Migration("20210127092028_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Synapse.Domain.Entities.Cre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDR_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONV_REF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_FAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ETAT_PRESTATION")
                        .HasColumnType("int");

                    b.Property<string>("EXR_SURV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_MESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIB_CNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNT_TOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAT_PREST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_FICH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_PIVOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_SOUS_COMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUM_FICH_BRIDGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUM_SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_DEB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_FIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIVOT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_GR_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERSION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreSet");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.Histories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColonneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Update_Group")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HistorySet");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.Ssa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDR_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_RMB_SCS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAT_ASSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DG_EVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DVS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DVS_REEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DVS_RMB_AUT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DVS_RMB_SCS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_EVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_PREST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_SEQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONV_REF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COT_ASSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreId")
                        .HasColumnType("int");

                    b.Property<string>("DT_FAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ETAT_PRESTATION")
                        .HasColumnType("int");

                    b.Property<string>("EXR_SURV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_MESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIB_CNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNT_TOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOIS_SURV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MT_AKT_MAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MT_AUT_RMB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MT_FRA_REEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MT_PREST_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MT_RMB_SS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NATEVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAT_PREST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NB_ACTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NB_ASSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_FICH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_PIVOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_SOUS_COMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUM_FICH_BRIDGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUM_SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_DEB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_FIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIVOT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEG_SSA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEX_ASSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TR_AGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_RMB_SCS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_GR_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERSION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreId");

                    b.ToTable("SsaSet");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.Ssa", b =>
                {
                    b.HasOne("Synapse.Domain.Entities.Cre", "Cre")
                        .WithMany("ListSsa")
                        .HasForeignKey("CreId");
                });
#pragma warning restore 612, 618
        }
    }
}
