// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synapse.Infrastructure;

namespace Synapse.Infrastructure.Migrations
{
    [DbContext(typeof(SynapseDBContext))]
    [Migration("20210202202307_UpdatePrestationCommun")]
    partial class UpdatePrestationCommun
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Synapse.Domain.Entities.CreAds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ADDR_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONV_REF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT_FAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ETAT_PRESTATION")
                        .HasColumnType("int");

                    b.Property<string>("EXR_SURV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FluxFileId")
                        .HasColumnType("int");

                    b.Property<string>("ID_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_MESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIB_CNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MNT_TOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAT_PREST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_FICH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_PIVOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_SOUS_COMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUM_FICH_BRIDGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUM_SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_DEB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_FIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIVOT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_GR_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERSION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FluxFileId");

                    b.ToTable("CreAds");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.CreDcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ADRESSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FluxFileId")
                        .HasColumnType("int");

                    b.Property<string>("LIGNE_SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MT_DEMAND")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MT_TOT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAIS_SOC_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAIS_SOC_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_DES_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIRET_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIRET_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FluxFileId");

                    b.ToTable("CreDcs");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.FluxFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PivotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PivotId");

                    b.ToTable("FluxFiles");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ColonneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateGroup")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.Pivot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NomPivot")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pivots");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.PrestationCommune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CreAdsId")
                        .HasColumnType("int");

                    b.Property<int?>("CreDcsId")
                        .HasColumnType("int");

                    b.Property<string>("EXR_SURV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOIS_SURV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MT_PREST_DG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PER_DEB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_FIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReservoirAccapPivotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreAdsId");

                    b.HasIndex("CreDcsId");

                    b.HasIndex("ReservoirAccapPivotId");

                    b.ToTable("PrestationCommunes");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.ReservoirAccapPivot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateSaisie")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricule_Apporteur_Gest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Bordereau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Ordre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReservoirAccapPivots");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.SsaAds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ADDR_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BASE_RMB_SCS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAT_ASSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DG_EVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DVS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DVS_REEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DVS_RMB_AUT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DVS_RMB_SCS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_EVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_PREST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_SEQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONV_REF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COT_ASSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreId")
                        .HasColumnType("int");

                    b.Property<string>("DT_FAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ETAT_PRESTATION")
                        .HasColumnType("int");

                    b.Property<string>("EXR_SURV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_MESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIB_CNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNT_TOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOIS_SURV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MT_AKT_MAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MT_AUT_RMB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MT_FRA_REEL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MT_PREST_DG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MT_RMB_SS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NATEVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAT_PREST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NB_ACTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NB_ASSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_FICH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_PIVOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_SOUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_SOUS_COMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUM_FICH_BRIDGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUM_SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_DEB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_FIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIVOT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_DG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REF_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEG_SSA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEX_ASSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TR_AGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TX_RMB_SCS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_GR_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_RSQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERSION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreId");

                    b.ToTable("SsaAds");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.CreAds", b =>
                {
                    b.HasOne("Synapse.Domain.Entities.FluxFile", "FluxFile")
                        .WithMany()
                        .HasForeignKey("FluxFileId");

                    b.Navigation("FluxFile");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.CreDcs", b =>
                {
                    b.HasOne("Synapse.Domain.Entities.FluxFile", "FluxFile")
                        .WithMany()
                        .HasForeignKey("FluxFileId");

                    b.Navigation("FluxFile");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.FluxFile", b =>
                {
                    b.HasOne("Synapse.Domain.Entities.Pivot", "Pivot")
                        .WithMany()
                        .HasForeignKey("PivotId");

                    b.Navigation("Pivot");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.PrestationCommune", b =>
                {
                    b.HasOne("Synapse.Domain.Entities.CreAds", "CreAds")
                        .WithMany()
                        .HasForeignKey("CreAdsId");

                    b.HasOne("Synapse.Domain.Entities.CreDcs", "CreDcs")
                        .WithMany()
                        .HasForeignKey("CreDcsId");

                    b.HasOne("Synapse.Domain.Entities.ReservoirAccapPivot", "ReservoirAccapPivot")
                        .WithMany("PrestationCommunes")
                        .HasForeignKey("ReservoirAccapPivotId");

                    b.Navigation("CreAds");

                    b.Navigation("CreDcs");

                    b.Navigation("ReservoirAccapPivot");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.SsaAds", b =>
                {
                    b.HasOne("Synapse.Domain.Entities.CreAds", "Cre")
                        .WithMany("ListSsa")
                        .HasForeignKey("CreId");

                    b.Navigation("Cre");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.CreAds", b =>
                {
                    b.Navigation("ListSsa");
                });

            modelBuilder.Entity("Synapse.Domain.Entities.ReservoirAccapPivot", b =>
                {
                    b.Navigation("PrestationCommunes");
                });
#pragma warning restore 612, 618
        }
    }
}
